Cats99/config/routes.rb
Rails.application.routes.draw do

  resources :cats do
    resources :cat_rental_requests, only: [:create, :new] do
      post "approve", on: :member
      post "deny", on: :member
    end

    root to: redirect("/cats")
  end

end

Cats99/app/models/cat.rb
class Cat < ActiveRecord::Base
  COLORS = %w(black white grey brown orange)
  validates :name, presence: true, uniqueness: true
  validates :birth_date, presence: true
  validates :color, inclusion: { in: COLORS,
    message: "%{value} is not a valid color"}, presence: true
  validates :sex, inclusion: { in: %w(M F),
    message: "%{value} is not a valid sex"}, presence: true

  has_many :rentals,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: :CatRentalRequest,
    dependent: :destroy

  def age
    Date.today.year - self.birth_date.year
  end
end

Cats99/app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  STATUS = %w(PENDING APPROVED DENIED)
  validates :cat_id, :start_date, :end_date, presence: true
  validates :status, presence: true,
    inclusion: { in: STATUS, message: "Invalid Status." }
  validate :no_overlaps

  belongs_to :cat,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: :Cat

  def over_lapping_approved_requests
    @cat_rental_requests = CatRentalRequest.all
    @approved_requests = @cat_rental_requests.select do |request|
      request.status == "APPROVED"
    end

    @approved_requests.each do |request|
      next if request == self
      return true if over_lapping_requests(request)
    end

    false
  end

  def over_lapping_requests(other_request)
    if self.cat_id == other_request.cat_id && self != other_request
      return (other_request.start_date.between?(self.start_date, self.end_date) ||
        other_request.end_date.between?(self.start_date, self.end_date))
    end

    false
  end

  def approve!
    transaction do
      CatRentalRequest.all.each do |request|
        if self.over_lapping_requests(request)
          request.deny!
        end
      end

      self.update(status: 'APPROVED')
    end
  end

  def deny!
    self.update(status: 'DENIED')
  end

  private

  def no_overlaps
    if over_lapping_approved_requests
      errors[:overlapping_requests] << "are not allowed."
    end
  end
end

Cats99/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

Cats99/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def index
    @cat_rental_requests = CatRentalRequest.order(start_date: :asc)
    render :index
  end

  def create
    @cat_rental_request = CatRentalRequest.create(cat_rental_params)

    render :show
  end

  def new
    @cat_rental_request = CatRentalRequest.new
    @cats = Cat.all

    render :new
  end

  def update
    @cat_rental_request = CatRentalRequest.find_by(id: params[:id])
    @cat_rental_request.update(cat_rental_params)

    render :show
  end

  def show
    @cat_rental_request = CatRentalRequest.find_by(id: params[:id])

    render :show
  end

  def edit
    @cat_rental_request = CatRentalRequest.find_by(id: params[:id])

    render :edit
  end

  def approve
    @cat_rental_request = CatRentalRequest.find_by(id: params[:id])
    @cat_rental_request.approve!
  end

  def deny
    @cat_rental_request = CatRentalRequest.find_by(id: params[:id])
    @cat_rental_request.deny!
  end

  private

  def cat_rental_params
    params.require(:cat_rental_request).permit(:cat_id, :start_date, :end_date, :status)
  end
end

Cats99/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find_by(id: params[:id])
    render :show
  end

  def new
    @cat = Cat.new

    render :new
  end

  def create
    @cat = Cat.create(cat_params)

    render :show
  end

  def update
    @cat = Cat.find_by(id: params[:id])
    @cat.update(cat_params)

    render :show
  end

  def edit
    @cat = Cat.find_by(id: params[:id])

    render :edit
  end
  private

  def cat_params
    params.require(:cat).permit(:name, :sex, :color, :birth_date, :description)
  end
end

Cats99/app/helpers/application_helper.rb
module ApplicationHelper
end

Cats99/app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

Cats99/app/helpers/cats_helper.rb
module CatsHelper
end

Cats99/app/views/cat_rental_requests/index.html.erb
<h1>ALL CAT RENTALS</h1>

<ul>
  <% @cat_rental_requests.each do |request| %>
    <li>Cat ID: <%= request.cat_id %></li>
    <li>Start Date: <%= request.start_date %></li>
    <li>End Date: <%= request.end_date %></li>
    <li>Status: <%= request.status %></li>
    <br>
    <br>
  <% end %>
</ul>

Cats99/app/views/cat_rental_requests/new.html.erb
<h1>Add a new rental request!</h1>

<%= render "shared/rental_form", cats: @cats, cat_rental_request: @cat_rental_request,
 action: :create %>

Cats99/app/views/cat_rental_requests/show.html.erb
<h1>Cat Rental</h1>

<table>
  <colgroup span="5"></colgroup>
  <tr>
    <th>Cat ID</th>
    <th>Start date</th>
    <th>End date</th>
    <th>Status</th>

  </tr>
  <tr>
    <td><%= @cat_rental_request.cat_id %></td>
    <td><%= @cat_rental_request.start_date %></td>
    <td><%= @cat_rental_request.end_date %></td>
    <td><%= @cat_rental_request.status %></td>
  </tr>
</table>

Cats99/app/views/cats/edit.html.erb
<h1>Edit a cat!</h1>

<%= render "shared/form", cat: @cat, action: :edit %>

Cats99/app/views/cats/index.html.erb
<h1>C A T S</h1>

<ul>
  <% @cats.each do |cat| %>
    <li>Name: <%= cat.name %></li>
    <li>Age: <%= cat.age %></li>
    <li>Color: <%= cat.color %></li>
    <%= link_to "Show more info...", "/cats/#{cat.id}" %>
    <%#= button_to "Show more info...", cat_url(cat), method: :get %>
    <br>
    <br>
  <% end %>
</ul>

Cats99/app/views/cats/new.html.erb
<h1>Add a new cat!</h1>

<%= render "shared/form", cat: @cat, action: :create %>

Cats99/app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>

<table>
  <colgroup span="5"></colgroup>
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th>Color</th>
    <th>Sex</th>
    <th>Birthdate</th>
    <th>Description</th>
  </tr>
  <tr>
    <td><%= @cat.name %></td>
    <td><%= @cat.age %></td>
    <td><%= @cat.color %></td>
    <td><%= @cat.sex %></td>
    <td><%= @cat.birth_date %></td>
    <td><%= @cat.description %></td>
  </tr>
</table>

<form action="<%= cat_cat_rental_request_url(cat_rental_request) %>" method="post">
  <input name="_method" type="hidden" value="patch" />
  <label for="cat_rentals">Cat Rentals</label>
  <br>
  <select id="cat_rentals" name="cat_rental_request[id]">
    <option selected value=""></option>
    <% @cat.rentals.each do |rental| %>
      <% next unless rental.status == 'PENDING' %>
      <option value="<%= if rental.status == rental.id %>"><%= rental.start_date %><%= rental.end_date %></option>
    <% end %>
  </select>
  <input type="submit"/>
</form>
<p>

Cats99/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cats99</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Cats99/app/views/shared/_form.html.erb
<% if cat.persisted? %>
<form action="<%= cat_url(cat) %>" method="post">
  <input name="_method" type="hidden" value="patch" />
<% else %>
<form action="<%= cats_url %>" method="post">
<% end %>

  <label for="name">Name</label>
  <br>
  <input id="name" value="<%= cat.name %>" type="text" name="cat[name]">
  <p>

  <label for="sex">Sex</label>
  <br>
  <% if cat.sex == 'M'%>
  M<input id="sex" checked="true" type="radio" name="cat[sex]" value="M">
  F<input id="sex" type="radio" name="cat[sex]" value="F">
  <br>
  <% else %>
  M<input id="sex" type="radio" name="cat[sex]" value="M">
  F<input id="sex" checked="true" type="radio" name="cat[sex]" value="F">
  <% end %>
  <p>

  <label for="color">Color</label>
  <br>
  <select id="color" name="cat[color]">
    <option selected value=""></option>
    <option <%= 'selected' if cat.color == 'black' %> value="black">Black</option>
    <option <%= 'selected' if cat.color == 'white' %> value="white">White</option>
    <option <%= 'selected' if cat.color == 'grey' %> value="grey">Grey</option>
    <option <%= 'selected' if cat.color == 'brown' %> value="brown">Brown</option>
    <option <%= 'selected' if cat.color == 'orange' %> value="orange">Orange</option>
  </select>
  <p>

  <label for="birth_date">Birthdate</label>
  <br>
  <input id="birth_date" type="date" value="<%= cat.birth_date %>" name="cat[birth_date]">
  <p>

  <label for="description">Description</label>
  <br>
  <textarea name="cat[description]" id="description"><%= cat.description %></textarea>

  <p>
  <input type="submit"/>

</form>

Cats99/app/views/shared/_rental_form.html.erb
<% if cat_rental_request.persisted? %>
<form action="<%= cat_cat_rental_request_url(cat_rental_request) %>" method="post">
  <input name="_method" type="hidden" value="patch" />
<% else %>
<form action="<%= cat_cat_rental_requests_url %>" method="post">
<% end %>

  <label for="cat">Cat</label>
  <br>
  <select id="cat" name="cat_rental_request[cat_id]">
    <option selected value=""></option>
    <% cats.each do |cat| %>
      <option <%= 'selected' if cat.id == cat_rental_request.cat_id %> value="<%= cat.id %>"><%= cat.name %></option>
    <% end %>
  </select>
  <p>

  <label for="start_date">Start date</label>
  <br>
  <input id="start_date" type="date" value="<%= cat_rental_request.start_date %>" name="cat_rental_request[start_date]">
  <p>

  <label for="end_date">End date</label>
  <br>
  <input id="end_date" type="date" value="<%= cat_rental_request.end_date %>" name="cat_rental_request[end_date]">
  <p>
  <input type="submit"/>

</form>